ConfluencePS/Public/Get-WikiChildPages.ps1
Function simply outputs child pages by their parent page id.
Sadly, couldn't get -Expand option working.
=> New function "Get-WikiChildPages"

ConfluencePS/Public/Get-WikiSpace.ps1, Tests/ConfluencePS.Integration.Tests.ps1
* Allows for the space key to be provided without the parameter name
* Allows for multiple keys to be provided at once
fixes #26
=> Added positional parameter & more than one space key

ConfluencePS/Private/ConvertFrom-HTMLEncoded.ps1, ConfluencePS/Private/ConvertFrom-URLEncoded.ps1, ConfluencePS/Private/ConvertTo-GetParameter.ps1, ConfluencePS/Private/ConvertTo-HTMLEncoded.ps1, ConfluencePS/Private/ConvertTo-URLEncoded.ps1, ConfluencePS/Private/ConvertTo-WikiIcon.ps1, ConfluencePS/Private/ConvertTo-WikiLabel.ps1, ConfluencePS/Private/ConvertTo-WikiPage.ps1, ConfluencePS/Private/ConvertTo-WikiPageAncestor.ps1, ConfluencePS/Private/ConvertTo-WikiSpace.ps1, ConfluencePS/Private/ConvertTo-WikiUser.ps1, ConfluencePS/Private/ConvertTo-WikiVersion.ps1, ConfluencePS/Private/Invoke-WikiMethod.ps1, ConfluencePS/Public/Add-WikiLabel.ps1, ConfluencePS/Public/ConvertTo-WikiStorageFormat.ps1, ConfluencePS/Public/ConvertTo-WikiTable.ps1, ConfluencePS/Public/Get-WikiChildPage.ps1, ConfluencePS/Public/Get-WikiLabel.ps1, ConfluencePS/Public/Get-WikiPage.ps1, ConfluencePS/Public/Get-WikiSpace.ps1, ConfluencePS/Public/New-WikiPage.ps1, ConfluencePS/Public/New-WikiSpace.ps1, ConfluencePS/Public/Remove-WikiLabel.ps1, ConfluencePS/Public/Remove-WikiPage.ps1, ConfluencePS/Public/Remove-WikiSpace.ps1, ConfluencePS/Public/Set-WikiInfo.ps1, ConfluencePS/Public/Set-WikiLabel.ps1, ConfluencePS/Public/Set-WikiPage.ps1, Tests/ConfluencePS.Integration.Tests.ps1
This contains the following changes:
* leave verbose message about api URL to Invoke-WikiMethod #21
* harmonized debug messages about content of request #21
* harmonized debug messages for parameters #21
* harmonized names of variables #21
* minor tweaks #21
* harmonized `ConfirmImpact` #25
=> Feature: harminize debug info

ConfluencePS/Private/Invoke-WikiMethod.ps1
=> Fix a tab-completion error in splatting for self-invocation

ConfluencePS/ConfluencePS.psd1, ConfluencePS/ConfluencePS.psm1, ConfluencePS/Private/ConvertTo-Icon.ps1, ConfluencePS/Private/ConvertTo-Label.ps1, ConfluencePS/Private/ConvertTo-Page.ps1, ConfluencePS/Private/ConvertTo-PageAncestor.ps1, ConfluencePS/Private/ConvertTo-Space.ps1, ConfluencePS/Private/ConvertTo-User.ps1, ConfluencePS/Private/ConvertTo-Version.ps1, ConfluencePS/Private/Invoke-Method.ps1, ConfluencePS/Public/Add-Label.ps1, ConfluencePS/Public/ConvertTo-StorageFormat.ps1, ConfluencePS/Public/ConvertTo-Table.ps1, ConfluencePS/Public/Get-ChildPage.ps1, ConfluencePS/Public/Get-Label.ps1, ConfluencePS/Public/Get-Page.ps1, ConfluencePS/Public/Get-Space.ps1, ConfluencePS/Public/New-Page.ps1, ConfluencePS/Public/New-Space.ps1, ConfluencePS/Public/Remove-Label.ps1, ConfluencePS/Public/Remove-Page.ps1, ConfluencePS/Public/Remove-Space.ps1, ConfluencePS/Public/Set-Info.ps1, ConfluencePS/Public/Set-Label.ps1, ConfluencePS/Public/Set-Page.ps1, ConfluencePS/en-US/about_ConfluencePS.help.txt, README.md, Tests/ConfluencePS.Base.Tests.ps1, Tests/ConfluencePS.Integration.Tests.ps1
* Remove the prefix from all function (except from the comment based help)
* add DefaultPrefix to manifest with default valeu `Confluence`
=> Feature: rename prefix

ConfluencePS/Private/Invoke-Method.ps1
=> Fix name of functions that haven't been renamed properly

ConfluencePS/Public/ConvertTo-StorageFormat.ps1
this closes issue #62 
this requires #65
=> Allow for positional parameter in ConvertTo-StorageFormat

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
This PR adds two template file for github.
* template how a bug report should look like
* template how a PR should look like
=> Add template to new issue and new PR

ConfluencePS/Public/Get-Page.ps1, Tests/ConfluencePS.Integration.Tests.ps1, docs/en-US/Get-Page.md
Allow Page search by title to be case insensitive and to accept wildcards
closes #74
=> Enhance: Get-ConfluencePage -Title string matching

CHANGELOG.md, ConfluencePS.build.ps1, ConfluencePS/ConfluencePS.psd1, README.md, appveyor.yml
`ItsHappening.gif`
1. Updated changelog with 2.0 details
- I'm sure I missed things. It could use extra eyes
- Set a release date of 2017/08/16; needs to be updated if we postpone
2. Updated the readme
- Maybe we want to add some common AtlassianPS info/sections?
3. Updated module manifest file:
1. Release notes link, pointing at the changelog file
2. Bumped version to 2.0.0 🎉
Working on #43.
Shipping 2.0 before the impending nuclear holocaust would be preferable 🤷‍♂️
=> Prepare module for 2.0 release

CHANGELOG.md, docs/en-US/about_ConfluencePS.md
Update the `about_ConfluencePS` help topic to reflect changes in `v2.0`.
Further doc updates as part of #43 that I forgot about.
=> Update the about help topic

ConfluencePS/ConfluencePS.Types.cs, Tests/ConfluencePS.Integration.Tests.ps1
Overwrite `ToString()` method in the custom classes of the module in order to get meaningful information when viewing nested objects
closes #92
=> Overwrite ToString() method of custom classes

ConfluencePS/Private/Invoke-Method.ps1
Show a warning to the user in case the server requires him to provide a captcha
closes #91
=> Warn in case the server requires a captcha

CHANGELOG.md, ConfluencePS/ConfluencePS.Types.cs, ConfluencePS/ConfluencePS.psd1, ConfluencePS/Private/Invoke-Method.ps1, Tests/ConfluencePS.Integration.Tests.ps1, appveyor.yml
IMPROVEMENTS:
- Shows a warning when the server requires a CAPTCHA for the authentication (#91, [@lipkau][])
- Custom classes now print relevant data in `ToString()` (#92, [@lipkau][])
closes #91 
closes #92
closes #97
=> Release v2.1

ConfluencePS/ConfluencePS.psd1
Ensure the System.Web assembly is loaded
closes #102
=> Ensure System.Web is loaded

ConfluencePS/Private/Invoke-Method.ps1, Tests/ConfluencePS.Integration.Tests.ps1
* PowerShell is not setting the encoding to UTF-8 for application/json
* See https://github.com/PowerShell/PowerShell/issues/5530
closes #101
=> Fix encoding of Invoke-WebRequest response

docs/classes/ConfluencePS.ContentLabelSet.md, docs/classes/ConfluencePS.Icon.md, docs/classes/ConfluencePS.Label.md, docs/classes/ConfluencePS.Page.md, docs/classes/ConfluencePS.Space.md, docs/classes/ConfluencePS.User.md, docs/classes/ConfluencePS.Version.md
Adds documents for each of the custom classes in ConfluencePS
Have a clear documentation on how to use the ConfluencePS classes.  
This documentation will be available @ https://atlassianps.org/docs/ConfluencePS/ once merged
=> Add documentation of ConfluencePS classes

ConfluencePS/Private/ConvertTo-Page.ps1, ConfluencePS/Public/Get-Page.ps1, Tests/ConfluencePS.Integration.Tests.ps1, docs/commands/Get-Page.md
* Adds new parameter for `Get-Page`: `-Query`
- this allows for CQL searches (including titles with wildcards)
=> Query for page

ConfluencePS/ConfluencePS.Types.cs, ConfluencePS/ConfluencePS.psd1, ConfluencePS/ConfluencePS.psm1, ConfluencePS/Private/ConvertFrom-HTMLEncoded.ps1, ConfluencePS/Private/Invoke-Method.ps1, ConfluencePS/Private/Invoke-WebRequest.ps1, ConfluencePS/Private/Test-Captcha.ps1, ConfluencePS/Private/Write-DebugMessage.ps1, Tests/ConfluencePS.Integration.Tests.ps1, Tests/ConfluencePS.Tests.ps1, appveyor.yml
This introduces full support for pwsh for linux (as far as the Integration Tests tell me).
Support PowerShell Core on other OS.
=> Support pwsh (PowerShell Core)

CHANGELOG.md, ConfluencePS.build.ps1, ConfluencePS/ConfluencePS.Types.cs, ConfluencePS/ConfluencePS.psd1, ConfluencePS/ConfluencePS.psm1, ConfluencePS/Private/ConvertFrom-HTMLEncoded.ps1, ConfluencePS/Private/ConvertTo-Page.ps1, ConfluencePS/Private/Invoke-Method.ps1, ConfluencePS/Private/Invoke-WebRequest.ps1, ConfluencePS/Private/Test-Captcha.ps1, ConfluencePS/Private/Write-DebugMessage.ps1, ConfluencePS/Public/Get-Page.ps1, Tests/ConfluencePS.Integration.Tests.ps1, Tests/ConfluencePS.Tests.ps1, appveyor.yml, docs/commands/Get-Page.md
- Automatic deployment of documentation to website (#120, [@lipkau][])
- New parameter `-Query` to `Get-Page` for complex searches (#106, [@lipkau][])
- Documentation for the custom classes of the module (#107, [@lipkau][])
- Added full support for PowerShell Core (`pwsh`) (#119, [@lipkau][])
- Fixed encoding of Unicode chars (#101, [@lipkau][])
- Require necessary Assembly for HttpUtility (#102, [@lipkau][])
=> Release v2.2

ConfluencePS/Public/Invoke-Method.ps1, docs/commands/Add-Attachment.md, docs/commands/Add-Label.md, docs/commands/ConvertTo-StorageFormat.md, docs/commands/ConvertTo-Table.md, docs/commands/Get-Attachment.md, docs/commands/Get-AttachmentFile.md, docs/commands/Get-ChildPage.md, docs/commands/Get-Label.md, docs/commands/Get-Page.md, docs/commands/Get-Space.md, docs/commands/Invoke-Method.md, docs/commands/New-Page.md, docs/commands/New-Space.md, docs/commands/Remove-Attachment.md, docs/commands/Remove-Label.md, docs/commands/Remove-Page.md, docs/commands/Remove-Space.md, docs/commands/Set-Attachment.md, docs/commands/Set-Info.md, docs/commands/Set-Label.md, docs/commands/Set-Page.md, docs/commands/about_ConfluencePS.md
* Made `Invoke-Method` a public function with proper documentation.
* Changed cmdlet help to use the homepage for the online help.
`Invoke-Method` can be a useful tool for 3rd-party developers that intend to communicate with endpoints that are not in scope of `ConfluencePS` (these are mainly plugins for Confluence).
=> Feature: Public Invoke-Method

ConfluencePS.build.ps1, ConfluencePS/ConfluencePS.psm1
Compilation of psm1 file needs the #region tags to know what to keep.
closes #132
=> Added regions in psm1 file for compilation

ConfluencePS/Private/ConvertTo-Attachment.ps1, Tests/ConfluencePS.Tests.ps1, docs/commands/Add-Attachment.md, docs/commands/Add-Label.md, docs/commands/ConvertTo-StorageFormat.md, docs/commands/ConvertTo-Table.md, docs/commands/Get-Attachment.md, docs/commands/Get-AttachmentFile.md, docs/commands/Get-ChildPage.md, docs/commands/Get-Label.md, docs/commands/Get-Page.md, docs/commands/Get-Space.md, docs/commands/Invoke-Method.md, docs/commands/New-Page.md, docs/commands/New-Space.md, docs/commands/Remove-Attachment.md, docs/commands/Remove-Label.md, docs/commands/Remove-Page.md, docs/commands/Remove-Space.md, docs/commands/Set-Attachment.md, docs/commands/Set-Info.md, docs/commands/Set-Label.md, docs/commands/Set-Page.md, docs/commands/about_ConfluencePS.md
* This improves the markdown linter results in the external help files.
* Remove `Description` header in examples
* Minor fixes in samples
=> Improved Markdown of Help

README.md
Fixes SVG icon for AppVeyor status
=> Fix icon for CI

ConfluencePS/Public/ConvertTo-Table.ps1
if the input object contains empty "cells" the function throws an error or creates tables with nested tables instead empty cells.
with this fix empty cells are filled with an space. this solves both problems.
replace empty cells with an space.
to reproduce you can use this data:
`$collection = [pscustomobject] @{ Column1 = 'Cell1'; Coulumn2 =  ''; Coloumn3 = 'Cell3' }`
or
[Collection.zip](https://github.com/AtlassianPS/ConfluencePS/files/2351810/Collection.zip)
`$collection = Import-Clixml .\Collection.xml`
or
[XLS.xlsx](https://github.com/AtlassianPS/ConfluencePS/files/2351808/XLS.xlsx)
`import-module psexcel #https://github.com/RamblingCookieMonster/PSExcel`
`$Collection = import-xlsx XLS.xlsx`
now lets convert this to an confluencetable
`import-module ConfluencePS `
`$collection = …
=> fix for tables with empty cells

ConfluencePS/Private/Set-TlsLevel.ps1, ConfluencePS/Public/Invoke-Method.ps1
Added support for TLS1.2 encrypted http requests
closes #143
=> Add support for TLS1.2

ConfluencePS/Public/Invoke-Method.ps1
Fix trailing Slash when URi does not include a path
closes #155
=> Fix trailing slash in base url

ConfluencePS/Public/ConvertTo-Table.ps1, Tests/Functions/ConvertTo-Table.Tests.ps1
=> Fix multiple header in table
